import { NextRequest, NextResponse } from 'next/server';

// GET /api/bookings/nationalities - Get all nationalities
export async function GET(request: NextRequest) {
  try {
    // Common nationalities list
    const nationalities = [
      { code: 'SA', name: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية' },
      { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة' },
      { code: 'KW', name: 'Kuwait', nameAr: 'الكويت' },
      { code: 'QA', name: 'Qatar', nameAr: 'قطر' },
      { code: 'BH', name: 'Bahrain', nameAr: 'البحرين' },
      { code: 'OM', name: 'Oman', nameAr: 'عمان' },
      { code: 'JO', name: 'Jordan', nameAr: 'الأردن' },
      { code: 'LB', name: 'Lebanon', nameAr: 'لبنان' },
      { code: 'SY', name: 'Syria', nameAr: 'سوريا' },
      { code: 'IQ', name: 'Iraq', nameAr: 'العراق' },
      { code: 'EG', name: 'Egypt', nameAr: 'مصر' },
      { code: 'LY', name: 'Libya', nameAr: 'ليبيا' },
      { code: 'TN', name: 'Tunisia', nameAr: 'تونس' },
      { code: 'DZ', name: 'Algeria', nameAr: 'الجزائر' },
      { code: 'MA', name: 'Morocco', nameAr: 'المغرب' },
      { code: 'SD', name: 'Sudan', nameAr: 'السودان' },
      { code: 'YE', name: 'Yemen', nameAr: 'اليمن' },
      { code: 'PS', name: 'Palestine', nameAr: 'فلسطين' },
      { code: 'US', name: 'United States', nameAr: 'الولايات المتحدة' },
      { code: 'GB', name: 'United Kingdom', nameAr: 'المملكة المتحدة' },
      { code: 'FR', name: 'France', nameAr: 'فرنسا' },
      { code: 'DE', name: 'Germany', nameAr: 'ألمانيا' },
      { code: 'IT', name: 'Italy', nameAr: 'إيطاليا' },
      { code: 'ES', name: 'Spain', nameAr: 'إسبانيا' },
      { code: 'NL', name: 'Netherlands', nameAr: 'هولندا' },
      { code: 'BE', name: 'Belgium', nameAr: 'بلجيكا' },
      { code: 'CH', name: 'Switzerland', nameAr: 'سويسرا' },
      { code: 'AT', name: 'Austria', nameAr: 'النمسا' },
      { code: 'SE', name: 'Sweden', nameAr: 'السويد' },
      { code: 'NO', name: 'Norway', nameAr: 'النرويج' },
      { code: 'DK', name: 'Denmark', nameAr: 'الدنمارك' },
      { code: 'FI', name: 'Finland', nameAr: 'فنلندا' },
      { code: 'PL', name: 'Poland', nameAr: 'بولندا' },
      { code: 'CZ', name: 'Czech Republic', nameAr: 'التشيك' },
      { code: 'HU', name: 'Hungary', nameAr: 'المجر' },
      { code: 'RO', name: 'Romania', nameAr: 'رومانيا' },
      { code: 'BG', name: 'Bulgaria', nameAr: 'بلغاريا' },
      { code: 'GR', name: 'Greece', nameAr: 'اليونان' },
      { code: 'TR', name: 'Turkey', nameAr: 'تركيا' },
      { code: 'RU', name: 'Russia', nameAr: 'روسيا' },
      { code: 'UA', name: 'Ukraine', nameAr: 'أوكرانيا' },
      { code: 'BY', name: 'Belarus', nameAr: 'بيلاروسيا' },
      { code: 'LT', name: 'Lithuania', nameAr: 'ليتوانيا' },
      { code: 'LV', name: 'Latvia', nameAr: 'لاتفيا' },
      { code: 'EE', name: 'Estonia', nameAr: 'إستونيا' },
      { code: 'CN', name: 'China', nameAr: 'الصين' },
      { code: 'JP', name: 'Japan', nameAr: 'اليابان' },
      { code: 'KR', name: 'South Korea', nameAr: 'كوريا الجنوبية' },
      { code: 'IN', name: 'India', nameAr: 'الهند' },
      { code: 'PK', name: 'Pakistan', nameAr: 'باكستان' },
      { code: 'BD', name: 'Bangladesh', nameAr: 'بنغلاديش' },
      { code: 'LK', name: 'Sri Lanka', nameAr: 'سريلانكا' },
      { code: 'NP', name: 'Nepal', nameAr: 'نيبال' },
      { code: 'MM', name: 'Myanmar', nameAr: 'ميانمار' },
      { code: 'TH', name: 'Thailand', nameAr: 'تايلاند' },
      { code: 'VN', name: 'Vietnam', nameAr: 'فيتنام' },
      { code: 'LA', name: 'Laos', nameAr: 'لاوس' },
      { code: 'KH', name: 'Cambodia', nameAr: 'كمبوديا' },
      { code: 'MY', name: 'Malaysia', nameAr: 'ماليزيا' },
      { code: 'SG', name: 'Singapore', nameAr: 'سنغافورة' },
      { code: 'ID', name: 'Indonesia', nameAr: 'إندونيسيا' },
      { code: 'PH', name: 'Philippines', nameAr: 'الفلبين' },
      { code: 'BN', name: 'Brunei', nameAr: 'بروناي' },
      { code: 'AU', name: 'Australia', nameAr: 'أستراليا' },
      { code: 'NZ', name: 'New Zealand', nameAr: 'نيوزيلندا' },
      { code: 'CA', name: 'Canada', nameAr: 'كندا' },
      { code: 'MX', name: 'Mexico', nameAr: 'المكسيك' },
      { code: 'BR', name: 'Brazil', nameAr: 'البرازيل' },
      { code: 'AR', name: 'Argentina', nameAr: 'الأرجنتين' },
      { code: 'CL', name: 'Chile', nameAr: 'تشيلي' },
      { code: 'PE', name: 'Peru', nameAr: 'بيرو' },
      { code: 'CO', name: 'Colombia', nameAr: 'كولومبيا' },
      { code: 'VE', name: 'Venezuela', nameAr: 'فنزويلا' },
      { code: 'UY', name: 'Uruguay', nameAr: 'أوروغواي' },
      { code: 'PY', name: 'Paraguay', nameAr: 'باراغواي' },
      { code: 'BO', name: 'Bolivia', nameAr: 'بوليفيا' },
      { code: 'EC', name: 'Ecuador', nameAr: 'الإكوادور' },
      { code: 'ZA', name: 'South Africa', nameAr: 'جنوب أفريقيا' },
      { code: 'NG', name: 'Nigeria', nameAr: 'نيجيريا' },
      { code: 'KE', name: 'Kenya', nameAr: 'كينيا' },
      { code: 'ET', name: 'Ethiopia', nameAr: 'إثيوبيا' },
      { code: 'GH', name: 'Ghana', nameAr: 'غانا' },
      { code: 'UG', name: 'Uganda', nameAr: 'أوغندا' },
      { code: 'TZ', name: 'Tanzania', nameAr: 'تنزانيا' },
      { code: 'RW', name: 'Rwanda', nameAr: 'رواندا' },
      { code: 'ZW', name: 'Zimbabwe', nameAr: 'زيمبابوي' },
      { code: 'BW', name: 'Botswana', nameAr: 'بوتسوانا' },
      { code: 'NA', name: 'Namibia', nameAr: 'ناميبيا' },
      { code: 'ZM', name: 'Zambia', nameAr: 'زامبيا' },
      { code: 'MW', name: 'Malawi', nameAr: 'مالاوي' },
      { code: 'MZ', name: 'Mozambique', nameAr: 'موزمبيق' },
      { code: 'MG', name: 'Madagascar', nameAr: 'مدغشقر' },
      { code: 'MU', name: 'Mauritius', nameAr: 'موريشيوس' },
      { code: 'SC', name: 'Seychelles', nameAr: 'سيشل' },
      { code: 'IR', name: 'Iran', nameAr: 'إيران' },
      { code: 'AF', name: 'Afghanistan', nameAr: 'أفغانستان' },
      { code: 'UZ', name: 'Uzbekistan', nameAr: 'أوزبكستان' },
      { code: 'KZ', name: 'Kazakhstan', nameAr: 'كازاخستان' },
      { code: 'KG', name: 'Kyrgyzstan', nameAr: 'قيرغيزستان' },
      { code: 'TJ', name: 'Tajikistan', nameAr: 'طاجيكستان' },
      { code: 'TM', name: 'Turkmenistan', nameAr: 'تركمانستان' },
      { code: 'AZ', name: 'Azerbaijan', nameAr: 'أذربيجان' },
      { code: 'AM', name: 'Armenia', nameAr: 'أرمينيا' },
      { code: 'GE', name: 'Georgia', nameAr: 'جورجيا' },
      { code: 'MD', name: 'Moldova', nameAr: 'مولدوفا' },
      { code: 'IL', name: 'Israel', nameAr: 'إسرائيل' },
      { code: 'CY', name: 'Cyprus', nameAr: 'قبرص' },
      { code: 'MT', name: 'Malta', nameAr: 'مالطا' },
      { code: 'IS', name: 'Iceland', nameAr: 'آيسلندا' },
      { code: 'IE', name: 'Ireland', nameAr: 'أيرلندا' },
      { code: 'PT', name: 'Portugal', nameAr: 'البرتغال' },
      { code: 'LU', name: 'Luxembourg', nameAr: 'لوكسمبورغ' },
      { code: 'LI', name: 'Liechtenstein', nameAr: 'ليختنشتاين' },
      { code: 'MC', name: 'Monaco', nameAr: 'موناكو' },
      { code: 'AD', name: 'Andorra', nameAr: 'أندورا' },
      { code: 'SM', name: 'San Marino', nameAr: 'سان مارينو' },
      { code: 'VA', name: 'Vatican City', nameAr: 'الفاتيكان' }
    ];

    // Sort alphabetically by name
    const sortedNationalities = nationalities.sort((a, b) => a.name.localeCompare(b.name));

    return NextResponse.json({
      success: true,
      data: sortedNationalities,
      count: sortedNationalities.length
    });
  } catch (error) {
    console.error('Error fetching nationalities:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: 'Failed to fetch nationalities',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}